name: u-boot-menu

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        arch: [aarch64]

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - uses: uraimo/run-on-arch-action@v2
      name: setup 
      with:
        arch: aarch64
        distro: ubuntu22.04
        run: |
           apt-get update
           apt install -y debhelper debhelper-compat
           ./build-deb-package
           echo "$(dpkg-parsechangelog -S Changes)" > DEBPKG.md
           cp ../u-boot-menu_$(dpkg-parsechangelog -S Version)_all.deb ./
           
    - name: check-Distribution
      run: |
        echo "distro=$(dpkg-parsechangelog -S Distribution)" >> $GITHUB_ENV
        echo "version=$(dpkg-parsechangelog -S Version)" >> $GITHUB_ENV
             
    - name: release
      if: env.distro != 'UNRELEASED'
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: u-boot-menu-v${{ env.version }}
        tag_name: v${{ env.version }}
        body_path: DEBPKG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: upload debian artifact
      if: env.distro != 'UNRELEASED'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: u-boot-menu_${{ env.version }}_all.deb
        asset_name: u-boot-menu_${{ env.version }}_all.deb
        asset_content_type: application/octet-stream
        
    - uses: actions/upload-artifact@v4
      name: setup artifact
      with:
        name: debian-package
        path: u-boot-menu_${{ env.version }}_all.deb
