name: Build & Release
on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get build-dep --no-install-recommends -y .
          CC=aarch64-linux-gnu- dpkg-buildpackage -a arm64 -d -b -nc -uc
      - name: Workaround actions/upload-artifact#176
        run: |
          echo "artifacts_path=$(realpath ..)" >> $GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ env.artifacts_path }}/*.deb
  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
      - name: Check if the latest version is releasable
        run: |
          version="$(dpkg-parsechangelog -S Version)"
          echo "version=$version" >> $GITHUB_ENV
          echo "changes<<EOF" >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          echo "$(dpkg-parsechangelog -S Changes)" >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          if [[ -n "$(git tag -l "$version")" ]]
          then
            echo "distro=UNRELEASED" >> $GITHUB_ENV
          else
            echo "distro=$(dpkg-parsechangelog -S Distribution)" >> $GITHUB_ENV
          fi
          echo "$version" > VERSION
      - name: Release
        if: env.distro != 'UNRELEASED'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: master
          draft: false
          fail_on_unmatched_files: false
          files: |
            *.deb
            VERSION
      - name: Append changelog
        if: env.distro != 'UNRELEASED'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body: |
            ## Changelog for ${{ env.version }}
            ${{ env.changes }}
          append_body: true
